In [1]:
##Import Libraries
import pandas as pd
import string 
import re
import nltk
from nltk.tokenize import word_tokenize
import pickle 

In [32]:
!gdown --id 1epokL1OkBNIyWIsGoDXjdrJVQw73zlAL

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1epokL1OkBNIyWIsGoDXjdrJVQw73zlAL
To: /content/wisata_bali.csv
100% 35.0k/35.0k [00:00<00:00, 41.3MB/s]


In [33]:
dataset=pd.read_csv("wisata_bali.csv")
dataset.head()

category                                             tags  \
0  ['Agrowisata']   Agrowisata, Gianyar, Dekat dari Bandara, Mahal   
1  ['Agrowisata']  Agrowisata, Gianyar, Sedang dari Bandara, Mahal   
2  ['Agrowisata']  Agrowisata, Denpasar, Dekat dari Bandara, Murah   
3  ['Agrowisata']  Agrowisata, Gianyar, Dekat dari Bandara, Gratis   
4  ['Agrowisata']  Agrowisata, Tabanan, Sedang dari Bandara, Murah   

   weekend_price  weekday_price distance  rating            place_name  \
0          50000          50000    dekat     3.0     Agrowisata Satria   
1         300000         300000   sedang     5.0      Aloha Ubud Swing   
2          35000          30000    dekat     4.0     Big Garden Corner   
3              0              0    dekat     4.5   Campuhan Ridge Walk   
4          40000          40000   sedang     4.5  Jatiluwih Green Land   

       city                                              image  \
0   Gianyar  https://i0.wp.com/sabani.com/wp-content/upload...   
1   Gianyar  https://static.cityspride.com/img/ruuu_1101/pr...   
2  Denpasar  https://www.rentalmobilbali.net/wp-content/upl...   
3   Gianyar  https://www.omnivagant.com/wp-content/uploads/...   
4   Tabanan  https://img.freepik.com/premium-photo/green-ri...   

                                         description  
0  ['Agrowisata Satria menawarkan 'rasa' Bali pad...  
1  ['Ajaklah orang-orang tercinta untuk mencoba a...  
2  ['Objek wisata Big Garden Corner Sanur adalah ...  
3  ['Campuhan Ridge Walk adalah sebuah trek joggi...  
4  ['Nominasi untuk penunjukan sebagai situs Wari...

In [34]:
dataset.shape

(75, 10)

In [35]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   category       75 non-null     object 
 1   tags           75 non-null     object 
 2   weekend_price  75 non-null     int64  
 3   weekday_price  75 non-null     int64  
 4   distance       75 non-null     object 
 5   rating         75 non-null     float64
 6   place_name     75 non-null     object 
 7   city           75 non-null     object 
 8   image          75 non-null     object 
 9   description    75 non-null     object 
dtypes: float64(1), int64(2), object(7)
memory usage: 6.0+ KB


# Pre-Processing

##Remove Character

In [36]:
#Remove Character Category
cat = dataset.category.apply(str)

def remove_character(data):
    return re.sub(r"'", "", data)

cat = cat.apply(remove_character)

def listToStringWithoutBrackets(data):
    return str(data).replace('[','').replace(']','')

cat = cat.apply(listToStringWithoutBrackets)

print(cat)

0     Agrowisata
1     Agrowisata
2     Agrowisata
3     Agrowisata
4     Agrowisata
         ...    
70      Religius
71      Religius
72      Religius
73      Religius
74      Religius
Name: category, Length: 75, dtype: object


In [38]:
#Remove Character Description
desc = dataset.description.apply(str)

def remove_character(data):
    return re.sub(r"'", "", data)

desc = desc.apply(remove_character)

def listToStringWithoutBrackets(data):
    return str(data).replace('[','').replace(']','')

desc = desc.apply(listToStringWithoutBrackets)

print(desc)

0     Agrowisata Satria menawarkan rasa Bali pada se...
1     Ajaklah orang-orang tercinta untuk mencoba ayu...
2     Objek wisata Big Garden Corner Sanur adalah se...
3     Campuhan Ridge Walk adalah sebuah trek jogging...
4     Nominasi untuk penunjukan sebagai situs Warisa...
                            ...                        
70    Pura Saraswati merupakan pura yang didirikan u...
71    Pura Taman Ayun di susun dengan konsep taman t...
72    Tirta Empul adalah nama sebuah pura Hindu yang...
73    Pura yang terletak di ujung barat daya pulau B...
74    Ada tiga hal utama yang ada di taman Tirta Gan...
Name: description, Length: 75, dtype: object


In [39]:
#save data
dataset['category'] = cat
dataset['description'] = desc
dataset

category                                             tags  \
0   Agrowisata   Agrowisata, Gianyar, Dekat dari Bandara, Mahal   
1   Agrowisata  Agrowisata, Gianyar, Sedang dari Bandara, Mahal   
2   Agrowisata  Agrowisata, Denpasar, Dekat dari Bandara, Murah   
3   Agrowisata  Agrowisata, Gianyar, Dekat dari Bandara, Gratis   
4   Agrowisata  Agrowisata, Tabanan, Sedang dari Bandara, Murah   
..         ...                                              ...   
70    Religius    Religius, Gianyar, Dekat dari Bandara, Gratis   
71    Religius      Religius, Badung, Dekat dari Bandara, Murah   
72    Religius    Religius, Gianyar, Sedang dari Bandara, Murah   
73    Religius      Religius, Badung, Dekat dari Bandara, Mahal   
74    Religius   Religius, Karangasem, Jauh dari Bandara, Murah   

    weekend_price  weekday_price distance  rating            place_name  \
0           50000          50000    dekat     3.0     Agrowisata Satria   
1          300000         300000   sedang     5.0      Aloha Ubud Swing   
2           35000          30000    dekat     4.0     Big Garden Corner   
3               0              0    dekat     4.5   Campuhan Ridge Walk   
4           40000          40000   sedang     4.5  Jatiluwih Green Land   
..            ...            ...      ...     ...                   ...   
70              0              0    dekat     4.0        Pura Saraswati   
71          15000          15000    dekat     4.0       Pura Taman Ayun   
72          30000          30000   sedang     4.5      Pura Tirta Empul   
73          50000          50000    dekat     4.0          Pura Uluwatu   
74          25000          25000     jauh     4.5          Tirta Gangga   

          city                                              image  \
0      Gianyar  https://i0.wp.com/sabani.com/wp-content/upload...   
1      Gianyar  https://static.cityspride.com/img/ruuu_1101/pr...   
2     Denpasar  https://www.rentalmobilbali.net/wp-content/upl...   
3      Gianyar  https://www.omnivagant.com/wp-content/uploads/...   
4      Tabanan  https://img.freepik.com/premium-photo/green-ri...   
..         ...                                                ...   
70     Gianyar  https://liburdulu.com/wp-content/uploads/2020/...   
71      Badung  https://img.freepik.com/free-photo/pura-taman-...   
72     Gianyar  https://media.istockphoto.com/id/1355012798/ph...   
73      Badung  https://museumnusantara.com/wp-content/uploads...   
74  Karangasem  https://s3.ap-southeast-2.amazonaws.com/thebal...   

                                          description  
0   Agrowisata Satria menawarkan rasa Bali pada se...  
1   Ajaklah orang-orang tercinta untuk mencoba ayu...  
2   Objek wisata Big Garden Corner Sanur adalah se...  
3   Campuhan Ridge Walk adalah sebuah trek jogging...  
4   Nominasi untuk penunjukan sebagai situs Warisa...  
..                                                ...  
70  Pura Saraswati merupakan pura yang didirikan u...  
71  Pura Taman Ayun di susun dengan konsep taman t...  
72  Tirta Empul adalah nama sebuah pura Hindu yang...  
73  Pura yang terletak di ujung barat daya pulau B...  
74  Ada tiga hal utama yang ada di taman Tirta Gan...  

[75 rows x 10 columns]

In [40]:
dataset.to_csv("wisatabali.csv")

#Recommendation

In [41]:
# loading the data from the csv file to apandas dataframe
dataset = pd.read_csv("wisatabali.csv").dropna()
dataset.head()

Unnamed: 0    category                                             tags  \
0           0  Agrowisata   Agrowisata, Gianyar, Dekat dari Bandara, Mahal   
1           1  Agrowisata  Agrowisata, Gianyar, Sedang dari Bandara, Mahal   
2           2  Agrowisata  Agrowisata, Denpasar, Dekat dari Bandara, Murah   
3           3  Agrowisata  Agrowisata, Gianyar, Dekat dari Bandara, Gratis   
4           4  Agrowisata  Agrowisata, Tabanan, Sedang dari Bandara, Murah   

   weekend_price  weekday_price distance  rating            place_name  \
0          50000          50000    dekat     3.0     Agrowisata Satria   
1         300000         300000   sedang     5.0      Aloha Ubud Swing   
2          35000          30000    dekat     4.0     Big Garden Corner   
3              0              0    dekat     4.5   Campuhan Ridge Walk   
4          40000          40000   sedang     4.5  Jatiluwih Green Land   

       city                                              image  \
0   Gianyar  https://i0.wp.com/sabani.com/wp-content/upload...   
1   Gianyar  https://static.cityspride.com/img/ruuu_1101/pr...   
2  Denpasar  https://www.rentalmobilbali.net/wp-content/upl...   
3   Gianyar  https://www.omnivagant.com/wp-content/uploads/...   
4   Tabanan  https://img.freepik.com/premium-photo/green-ri...   

                                         description  
0  Agrowisata Satria menawarkan rasa Bali pada se...  
1  Ajaklah orang-orang tercinta untuk mencoba ayu...  
2  Objek wisata Big Garden Corner Sanur adalah se...  
3  Campuhan Ridge Walk adalah sebuah trek jogging...  
4  Nominasi untuk penunjukan sebagai situs Warisa...

In [42]:
def important_features(dataset):
    data=dataset.copy()
    for i in range(0, dataset.shape[0]):
        data["imp"]= data["category"]+" "+data["tags"]
    return data


In [16]:
data=important_features(dataset)

In [43]:
data.head()

Unnamed: 0    category                                          tags  \
0           0  Agrowisata   Agrowisata Gianyar Dekat dari Bandara Mahal   
1           1  Agrowisata  Agrowisata Gianyar Sedang dari Bandara Mahal   
2           2  Agrowisata  Agrowisata Denpasar Dekat dari Bandara Murah   
3           3  Agrowisata  Agrowisata Gianyar Dekat dari Bandara Gratis   
4           4  Agrowisata  Agrowisata Tabanan Sedang dari Bandara Murah   

   weekend_price  weekday_price distance  rating            place_name  \
0          50000          50000    dekat     3.0     Agrowisata Satria   
1         300000         300000   sedang     5.0      Aloha Ubud Swing   
2          35000          30000    dekat     4.0     Big Garden Corner   
3              0              0    dekat     4.5   Campuhan Ridge Walk   
4          40000          40000   sedang     4.5  Jatiluwih Green Land   

       city                                              image  \
0   Gianyar  https://drive.google.com/file/d/108VxoEhKsyV2_...   
1   Gianyar  https://drive.google.com/file/d/1bvzte6xbyb6Ey...   
2  Denpasar  https://drive.google.com/file/d/12UMKldf_s7zGI...   
3   Gianyar  https://drive.google.com/file/d/1eVpiUN3lv1uzV...   
4   Tabanan  https://drive.google.com/file/d/1vX9x5gLEmQKdg...   

                                         description  \
0  Agrowisata Satria menawarkan rasa Bali pada se...   
1  Ajaklah orang-orang tercinta untuk mencoba ayu...   
2  Objek wisata Big Garden Corner Sanur adalah se...   
3  Campuhan Ridge Walk adalah sebuah trek jogging...   
4  Nominasi untuk penunjukan sebagai situs Warisa...   

                                                 imp  ids  
0  Agrowisata Agrowisata Gianyar Dekat dari Banda...    0  
1  Agrowisata Agrowisata Gianyar Sedang dari Band...    1  
2  Agrowisata Agrowisata Denpasar Dekat dari Band...    2  
3  Agrowisata Agrowisata Gianyar Dekat dari Banda...    3  
4  Agrowisata Agrowisata Tabanan Sedang dari Band...    4

In [44]:
data["ids"]=[i for i in range(0,data.shape[0])]

##Importing vectoriser

In [45]:
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
vec=TfidfVectorizer()

In [46]:
vecs=vec.fit_transform(data["imp"].apply(lambda x: np.str_(x)))

In [47]:
vecs.shape

(75, 22)

In [48]:
from sklearn.metrics.pairwise import cosine_similarity

In [49]:
sim=cosine_similarity(vecs) 
print(sim)

[[1.         0.94080748 0.74973552 ... 0.14489381 0.22954495 0.03596026]
 [0.94080748 1.         0.69742859 ... 0.23535769 0.18249954 0.03517785]
 [0.74973552 0.69742859 1.         ... 0.09844467 0.0801377  0.0857113 ]
 ...
 [0.14489381 0.23535769 0.09844467 ... 1.         0.68465895 0.67118511]
 [0.22954495 0.18249954 0.0801377  ... 0.68465895 1.         0.59610147]
 [0.03596026 0.03517785 0.0857113  ... 0.67118511 0.59610147 1.        ]]


In [50]:
sim.shape##Columns represnt movie-ids and not rows

(75, 75)

In [51]:
sim[0][74]

0.03596026028903452

In [52]:
def recommend(place):
    place_id=data[data.category==place]["ids"].values[0]
    scores=list(enumerate(sim[place_id]))
    sorted_scores=sorted(scores,key=lambda x:x[1],reverse=True)
    sorted_scores=sorted_scores[0:5]
    place=[data[place[0]==data["ids"]]["place_name"].values[0] for place in sorted_scores]
    return place

In [53]:
def recommend_ten(place_list):
    first_five=[]
    count=0
    for place in place_list:
        if count > 4:
            break
        count+=1
        first_five.append(place)
    return first_five



In [57]:
categ = input('Enter your category : ')
lst=recommend(categ)
m=recommend_ten(lst)
m

Enter your category : Belanja


['Agung Bali',
 'Pabrik Kata-Kata Joger',
 'Galeri Seni Semar Kuning',
 'Pasar Seni Tradisional Ubud',
 'Pusat Kesenian Ukir Desa Mas']

##save data

In [58]:
# Save dataframe
pickle.dump(data.to_dict(), open('rec_wisata.pkl', 'wb'))

In [59]:
# Save similarity
pickle.dump(sim, open('similarity.pkl', 'wb'))